# Generated by Django 5.1.6 on 2025-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
