# Generated by Django 5.1.6 on 2025-03-07 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='The postal code must contain between 3 and 10 alphanumeric characters.', regex='^[A-Z0-9]{3,10}$')]),
        ),
    ]
