# Generated by Django 5.1.6 on 2025-03-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentchildrelation',
            old_name='child',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='student', through='api.ParentChildRelation', to='api.parent'),
        ),
    ]
