version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cantineconnect
      - POSTGRES_USER=cantineuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=cantineconnect
      - POSTGRES_USER=cantineuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://cantineuser:mypassword@db:5432/cantineconnect
      - DJANGO_SECRET_KEY=changecetsecret
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,backend,127.0.0.1
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
